# frozen_string_literal: true

require 'rails/generators'
require 'rails/generators/active_record'
require_relative '../generator_helpers'

module RubyLLM
  module Generators
    # Upgrades the schema generated by RubyLLM 1.16 to RubyLLM 2.0.
    class UpgradeGenerator < Rails::Generators::Base
      include Rails::Generators::Migration
      include RubyLLM::Generators::GeneratorHelpers

      MODEL_MAPPING_DEFAULTS = {
        chat: 'Chat',
        message: 'Message',
        model: 'Model',
        tool_call: 'ToolCall'
      }.freeze
      MODEL_MAPPING_TYPES = MODEL_MAPPING_DEFAULTS.keys.map(&:to_s).freeze

      namespace 'ruby_llm:upgrade'
      source_root File.expand_path('templates', __dir__)

      class_option :phase, type: :string, enum: %w[prepare backfill finish cleanup],
                           desc: 'Generate one upgrade phase; cleanup runs in a later deployment'
      class_option :mode, type: :string, enum: %w[rename copy], default: 'rename',
                          desc: 'Copy prepares and backfills online, with protected 1.16 rollback until cleanup'
      class_option :discard_incomplete_tool_calls, type: :boolean, default: false,
                                                   desc: 'Discard all incomplete legacy tool calls at copy finish'

      argument :model_mappings,
               type: :array,
               default: [],
               banner: 'chat:ChatName message:MessageName model:ModelName tool_call:ToolCallName'

      desc 'Upgrades a RubyLLM 1.16 Rails schema to 2.0'

      def self.next_migration_number(dirname)
        ::ActiveRecord::Generators::Base.next_migration_number(dirname)
      end

      def create_migration_files
        validate_cleanup_options
        parse_model_mappings(allowed_types: MODEL_MAPPING_TYPES, defaults: MODEL_MAPPING_DEFAULTS)
        say_status :models, resolved_model_mappings

        if copy_mode? && !options[:phase].in?(%w[backfill finish cleanup])
          template 'ruby_llm_upgrade.rb.tt', 'app/models/concerns/ruby_llm_upgrade.rb'
          template 'upgrade_initializer.rb.tt', 'config/initializers/ruby_llm_upgrade.rb'
        end

        phases = options[:phase] ? [options[:phase]] : %w[prepare backfill finish]
        phases.each do |phase|
          template = phase == 'backfill' ? 'backfill_v2_data' : "#{phase}_v2_upgrade"
          migration = phase == 'backfill' ? 'backfill_ruby_llm_v2_data' : "#{phase}_ruby_llm_v2_upgrade"
          migration_template "#{template}.rb.tt", "db/migrate/#{migration}.rb"
        end
      end

      def show_next_steps
        say_status :success, 'Upgrade prepared!', :green
        if copy_mode?
          say <<~INSTRUCTIONS

            Copy mode retains the legacy tables and a separate chat model reference.
            Install the generated RubyLLMUpgrade concern and initializer in BOTH the
            running 1.16 build and the 2.0 build BEFORE running prepare. Restart
            all affected 1.16 processes so they load the guards and explicit column
            selects. The guards protect whole conversations
            changed by 2.0. Direct SQL, bulk updates/deletes and attachment purges
            bypass these guards; review those application paths before upgrading.

            Rehearse prepare, backfill and finish on a production database copy.
            Run prepare and backfill from the 2.0 build while 1.16 serves traffic.
            Stop affected traffic, workers, scheduled jobs and retries BEFORE finish.
            Finish catches up intervening writes, validates and activates 2.0.
            Then load models and restart the 2.0 application.
            Keep the old model/tool-call classes in the 1.16 build.

            PostgreSQL, MySQL and SQLite support this workflow. Schema changes can
            block writes; SQLite also serializes backfill and app writes.
            Use a direct connection or session-mode pool for copy migrations.
            db:migrate runs ALL pending phases. Stop at the backfill timestamp to
            defer finish, or pause AI before running all three together.

            With all affected processes stopped, use the 2.0 build to run:
              bin/rails ruby_llm:upgrade:rollback  # activates the protected 1.16 view
              bin/rails ruby_llm:upgrade:resume    # reconciles 1.16 writes, activates 2.0

            Finish pending tool calls, approvals and batches before switching.
            Once rollback is no longer needed, run ruby_llm:upgrade:finalize, then
            generate --mode copy --phase cleanup in a later deployment. Keep the
            compatibility files until cleanup succeeds; remove them afterward.

            Pass the same --mode and model mappings to every generator invocation.
            Full guide: https://rubyllm.com/next/upgrading/

          INSTRUCTIONS
          return
        end
        say <<~INSTRUCTIONS

          These migrations expect the schema generated by RubyLLM 1.16. They move
          RubyLLM's model and tool-call records, preserve message content and usage,
          and retain the 1.x message columns until a later cleanup deployment.

          Next steps:
          1. Review the generated migrations
          2. Rehearse them on a recent production snapshot
          3. Stop affected web processes, workers, scheduled jobs, and retries
          4. Run preparation, backfill, and finish before reopening traffic
          5. Run: bin/rails ruby_llm:load_models
          6. Keep only the current declarations in your application models:
             #{chat_model_path}: #{acts_as_chat_declaration}
             #{message_model_path}: #{acts_as_message_declaration}
          7. Remove the 1.x model and tool-call classes, config.model_registry_class,
             and config.use_new_acts_as
          8. Update 1.x API calls using the upgrade guide

          Generate one phase with --phase prepare, backfill, or finish when the
          backfill needs to run outside your deployment's release phase.
          After verifying the upgrade, generate --phase cleanup in a later release.
          Pass the same model mappings to every invocation.

          The migrations are irreversible. Retained columns do not make a code
          rollback safe; recovery requires the previous database and application.

          Full upgrade guide:
             https://rubyllm.com/next/upgrading/

        INSTRUCTIONS
      end

      private

      def copy_mode? = options[:mode] == 'copy'
      def discard_incomplete_tool_calls? = options[:discard_incomplete_tool_calls]

      def validate_cleanup_options
        return unless discard_incomplete_tool_calls?
        return if copy_mode? && options[:phase].in?([nil, 'finish'])

        raise Thor::Error, 'Discard incomplete tool calls only with --mode copy and the finish phase'
      end

      def copy_upgrade_settings
        {
          chat_table: chat_table_name, message_table: message_table_name,
          model_table: v1_model_table_name, tool_call_table: v1_tool_call_table_name,
          chat_class: chat_model_name, message_class: message_model_name,
          model_foreign_key: v1_model_foreign_key, tool_call_foreign_key: v1_tool_call_foreign_key,
          chat_foreign_key: chat_foreign_key, message_foreign_key: message_foreign_key
        }
      end

      def prepare_migration_class_name = 'prepare_ruby_llm_v2_upgrade'.camelize
      def backfill_migration_class_name = 'backfill_ruby_llm_v2_data'.camelize
      def finish_migration_class_name = 'finish_ruby_llm_v2_upgrade'.camelize
      def cleanup_migration_class_name = 'cleanup_ruby_llm_v2_upgrade'.camelize

      def resolved_model_mappings
        @model_names.map do |type, model_name|
          "#{type}:#{model_name} -> #{table_name_for(model_name)}"
        end.join(', ')
      end

      def v1_model_name(type)
        @model_names.fetch(type)
      end

      def v1_model_table_name = table_name_for(v1_model_name(:model))
      def v1_tool_call_table_name = table_name_for(v1_model_name(:tool_call))
      def v1_model_foreign_key = "#{v1_model_table_name.singularize}_id"
      def v1_tool_call_foreign_key = "#{v1_tool_call_table_name.singularize}_id"
      def message_foreign_key = "#{message_table_name.singularize}_id"
      def chat_foreign_key = "#{chat_table_name.singularize}_id"

      def chat_model_path
        "app/models/#{chat_model_name.underscore}.rb"
      end

      def message_model_path
        "app/models/#{message_model_name.underscore}.rb"
      end
    end
  end
end
